-- MySQL Script generated by MySQL Workbench
-- Sun May 19 14:54:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sjreal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sjreal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sjreal` DEFAULT CHARACTER SET utf8 ;
USE `sjreal` ;

-- -----------------------------------------------------
-- Table `sjreal`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`personas` (
  `id_persona` INT NOT NULL,
  `nombre_persona` VARCHAR(45) NOT NULL,
  `apellido_persona` VARCHAR(55) NOT NULL,
  `documento_persona` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correo_persona` VARCHAR(70) NOT NULL,
  `tipo_documento` ENUM("cedula de ciudadania", "targeta de indentidad", "cedula de extrangeria", "pasaporte", "NUIP") NOT NULL DEFAULT "cedula de ciudadania",
  `nacionalidad` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`roles` (
  `id_rol` INT NOT NULL,
  `name_rol` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`roles_has_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`roles_has_usuarios` (
  `id_rol_usuario` INT NOT NULL,
  `roles_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_rol_usuario`),
  CONSTRAINT `fk_roles_has_usuarios_roles1`
    FOREIGN KEY (`roles_id_rol`)
    REFERENCES `sjreal`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`usuarios` (
  `id_usuario` INT NOT NULL,
  `usuario_id_persona` INT NOT NULL,
  `usuarios_id_rol_usuario` INT NOT NULL,
  `contrasena_usuario` VARCHAR(20) NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_usuarios_personas1`
    FOREIGN KEY (`usuario_id_persona`)
    REFERENCES `sjreal`.`personas` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_roles_has_usuarios1`
    FOREIGN KEY (`usuarios_id_rol_usuario`)
    REFERENCES `sjreal`.`roles_has_usuarios` (`id_rol_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`sucursales` (
  `id_sucursal` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_sucursal` INT NOT NULL,
  `NIT_sucursal` VARCHAR(15) NOT NULL,
  `nombre_sucursal` VARCHAR(50) NOT NULL,
  `departamento_sucursal` ENUM('Amazonas', 'Antioquia', 'Arauca', 'Atlántico', 'Bolívar', 'Boyacá', 'Caldas', 'Caquetá', 'Casanare', 'Cauca', 'Cesar', 'Chocó', 'Córdoba', 'Cundinamarca', 'Guainía', 'Guaviare', 'Huila', 'La Guajira', 'Magdalena', 'Meta', 'Nariño', 'Norte de Santander', 'Putumayo', 'Quindío', 'Risaralda', 'San Andrés y Providencia', 'Santander', 'Sucre', 'Tolima', 'Valle del Cauca', 'Vaupés', 'Vichada') NOT NULL,
  `cuidad_sucursal` VARCHAR(50) NOT NULL,
  `calle_sucursal` INT NOT NULL,
  `carrera_sucursal` INT NOT NULL,
  `telefono_sucursal` VARCHAR(10) NOT NULL,
  `correo_sucursal` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_sucursal`),
  CONSTRAINT `fk_Sucursal_usuarios1`
    FOREIGN KEY (`usuario_id_sucursal`)
    REFERENCES `sjreal`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `precio_producto` DECIMAL(10) NOT NULL,
  `descripcion_producto` VARCHAR(200) NOT NULL,
  `nombre_producto` VARCHAR(50) NOT NULL,
  `estado_producto` ENUM('Activo', 'Inactivo') NOT NULL,
  `existencias_producto` INT NOT NULL,
  `maximo_producto` INT NOT NULL,
  `minimo_producto` INT NOT NULL,
  `tipo_producto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`control_inventarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`control_inventarios` (
  `id_control_inventario` INT NOT NULL AUTO_INCREMENT,
  `control_inventario_id_producto` INT NOT NULL,
  `fecha_actualizacion` DATE NOT NULL,
  `tipop_actualizacion` ENUM('Modificar cantidad producto', 'Añadir nuevo Item', 'Eliminar Item') NOT NULL,
  `cantidad_añadida` INT NOT NULL,
  `cantidad_restada` INT NOT NULL,
  PRIMARY KEY (`id_control_inventario`),
  CONSTRAINT `fk_control_inventarios_productos1`
    FOREIGN KEY (`control_inventario_id_producto`)
    REFERENCES `sjreal`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`iventarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`iventarios` (
  `id_inventario` INT NOT NULL AUTO_INCREMENT,
  `control_rio_idControl_Inventario` INT NOT NULL,
  `cantidad_inventarios` INT NOT NULL,
  `nombre_Inventario` VARCHAR(45) NOT NULL,
  `categoria_Inventario` VARCHAR(45) NOT NULL,
  `inventario_sucersal_id_sucursal` INT NOT NULL,
  PRIMARY KEY (`id_inventario`),
  CONSTRAINT `fk_Sucursal_has_Inventario_Control_Inventario1`
    FOREIGN KEY (`control_rio_idControl_Inventario`)
    REFERENCES `sjreal`.`control_inventarios` (`id_control_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sucursal_has_inventario_sucursales1`
    FOREIGN KEY (`inventario_sucersal_id_sucursal`)
    REFERENCES `sjreal`.`sucursales` (`id_sucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`habitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`habitaciones` (
  `id_habitacion` INT NOT NULL AUTO_INCREMENT,
  `numero_habitacion` VARCHAR(3) NOT NULL,
  `descripcion_habitacion` VARCHAR(500) NOT NULL,
  `tipo_habitacion` ENUM('Sencilla', 'Doble', 'Para pareja') NOT NULL,
  `capacidad_habitacion` INT NOT NULL,
  `precio_habitacion` DECIMAL(10) NOT NULL,
  `habitacion_id_sucursal` INT NOT NULL,
  PRIMARY KEY (`id_habitacion`),
  CONSTRAINT `fk_habitaciones_sucursales1`
    FOREIGN KEY (`habitacion_id_sucursal`)
    REFERENCES `sjreal`.`sucursales` (`id_sucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`Huesped`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`Huesped` (
  `idHuesped` INT NOT NULL AUTO_INCREMENT,
  `cedula _Huesped` VARCHAR(15) NOT NULL,
  `primer_Nombre_Huesped` VARCHAR(40) NOT NULL,
  `segundo_Nombre_Huesped` VARCHAR(40) NULL,
  `primer_Apellido_Huesped` VARCHAR(45) NOT NULL,
  `segundo_Apellido_Huesped` VARCHAR(45) NULL,
  `tipo_Documento_Huesped` ENUM('CC', 'CE', 'TI', 'Pasaporte') NOT NULL,
  `fecha_Nacimiento_Huesped` DATE NOT NULL,
  `edad_Huesped` INT NOT NULL,
  `telefono_Huesped` VARCHAR(15) NOT NULL,
  `correo_Huesped` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idHuesped`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`hospedajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`hospedajes` (
  `id_hospedaje` INT NOT NULL AUTO_INCREMENT,
  `habitacion_i_habitacion` INT NOT NULL,
  `usuarios_personas_id_persona` INT NOT NULL,
  `check_in_hospedaje` DATETIME(2) NOT NULL,
  `check_out_hospedaje` DATETIME(2) NOT NULL,
  `cantidad_habitaciones_hospedaje` INT NOT NULL,
  `cantidad_personas_hospedaje` INT NOT NULL,
  `dias_hospedaje` INT NOT NULL,
  `estado_hospedaje` ENUM('Cancelado', 'Abonado', 'Pagado') NOT NULL,
  PRIMARY KEY (`id_hospedaje`),
  CONSTRAINT `fk_Habitacion_has_Huesped_Habitacion1`
    FOREIGN KEY (`habitacion_i_habitacion`)
    REFERENCES `sjreal`.`habitaciones` (`id_habitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospedaje_usuarios1`
    FOREIGN KEY (`usuarios_personas_id_persona`)
    REFERENCES `sjreal`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`vehiculos` (
  `placa_vehiculo` VARCHAR(10) NOT NULL,
  `vehiculo_id_usuario` INT NOT NULL,
  `modelo_vehiculo` VARCHAR(45) NOT NULL,
  `color_vehiculo` VARCHAR(25) NOT NULL,
  `origen_vehiculo` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`placa_vehiculo`),
  CONSTRAINT `fk_Vehiculo_usuarios1`
    FOREIGN KEY (`vehiculo_id_usuario`)
    REFERENCES `sjreal`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`pagos` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `pago_id_hospedaje` INT NOT NULL,
  `pago_id_persona` INT NOT NULL,
  `titular_pago` VARCHAR(80) NOT NULL,
  `medio_pago` ENUM('PSE', 'Tarjeta de crédito', 'Tarjeta de dédito', 'Efectivo') NOT NULL,
  `concepto_pago` VARCHAR(500) NOT NULL,
  `total_pago` DECIMAL(10) NOT NULL,
  `tipo_cliente` ENUM('Persona natural', 'Persona jurídica') NOT NULL,
  PRIMARY KEY (`id_pago`),
  CONSTRAINT `fk_Pago_usuarios1`
    FOREIGN KEY (`pago_id_persona`)
    REFERENCES `sjreal`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_hospedajes1`
    FOREIGN KEY (`pago_id_hospedaje`)
    REFERENCES `sjreal`.`hospedajes` (`id_hospedaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`proveedores` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `NIT_proveedor` VARCHAR(15) NOT NULL,
  `nombre_proveedor` VARCHAR(45) NOT NULL,
  `telefono_proveedor` VARCHAR(15) NOT NULL,
  `correo_proveedor` VARCHAR(45) NOT NULL,
  `categoria_proveedor` ENUM('Aseo', 'Textiles', '') NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`sucursales_has_proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`sucursales_has_proveedores` (
  `id_sucursales_has_proveedores` INT NOT NULL AUTO_INCREMENT,
  `sucursales_has_proveedores_id_sucursal` INT NOT NULL,
  `proveedores_id_proveedor` INT NOT NULL,
  `fecha_inicio_actividades` DATE NOT NULL,
  `antiguedad_actividades` INT NOT NULL,
  PRIMARY KEY (`id_sucursales_has_proveedores`),
  CONSTRAINT `fk_Sucursal_has_Proveedor_Sucursal1`
    FOREIGN KEY (`sucursales_has_proveedores_id_sucursal`)
    REFERENCES `sjreal`.`sucursales` (`id_sucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sucursales_has_proveedores_proveedores1`
    FOREIGN KEY (`proveedores_id_proveedor`)
    REFERENCES `sjreal`.`proveedores` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`pedidos` (
  `IdPedido` INT NOT NULL AUTO_INCREMENT,
  `pedido_id_usuario` INT NOT NULL,
  `pedido_id_control_inventario` INT NOT NULL,
  `pedido_id_proveedor` INT NOT NULL,
  `cantidad_producto` INT NOT NULL,
  `fecha_entrega` DATETIME NOT NULL,
  `precio_total_pedido` DECIMAL(10) NOT NULL,
  `precio_unitario_producto` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`IdPedido`),
  CONSTRAINT `fk_Proveedor_has_Producto_Proveedor1`
    FOREIGN KEY (`pedido_id_proveedor`)
    REFERENCES `sjreal`.`proveedores` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_usuarios1`
    FOREIGN KEY (`pedido_id_usuario`)
    REFERENCES `sjreal`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_control_inventarios1`
    FOREIGN KEY (`pedido_id_control_inventario`)
    REFERENCES `sjreal`.`control_inventarios` (`id_control_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`detalles_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`detalles_pago` (
  `id_Detalle_Pago` INT NOT NULL AUTO_INCREMENT,
  `detalle_pago_id_pago` INT NOT NULL,
  `detalle_pago_id_producto` INT NOT NULL,
  `precio_por_item` DECIMAL(10) NOT NULL,
  `cantidad_item` INT NOT NULL,
  `detalle_pago_precio_total` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`id_Detalle_Pago`),
  CONSTRAINT `fk_detalles_pago_pagos1`
    FOREIGN KEY (`detalle_pago_id_pago`)
    REFERENCES `sjreal`.`pagos` (`id_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalles_pago_productos1`
    FOREIGN KEY (`detalle_pago_id_producto`)
    REFERENCES `sjreal`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`PQRS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`PQRS` (
  `id_PQRS` INT NOT NULL,
  `pqrs_id_usuario` INT NOT NULL,
  `fecha_pqrs` DATETIME NULL,
  `tipo_pqrs` VARCHAR(45) NULL,
  `descripcion_pqrs` LONGTEXT NULL,
  `radicado_pqrs` VARCHAR(25) NULL,
  PRIMARY KEY (`id_PQRS`),
  CONSTRAINT `fk_PQRS_usuarios1`
    FOREIGN KEY (`pqrs_id_usuario`)
    REFERENCES `sjreal`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjreal`.`parqueadero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjreal`.`parqueadero` (
  `id_parqueadero` INT NOT NULL,
  `vehiculo_id_vehiculo` INT NOT NULL,
  `hospedaje_id_hospedaje` INT NOT NULL,
  PRIMARY KEY (`id_parqueadero`),
  CONSTRAINT `fk_vehiculos_has_hospedajes_hospedajes1`
    FOREIGN KEY (`hospedaje_id_hospedaje`)
    REFERENCES `sjreal`.`hospedajes` (`id_hospedaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
